service: Analytics-Node

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      migrate: true

functions:

  batchPutToTickets:
    handler: src/tickets.batchPutToTickets
    events:
      - http:
          path: putTickets
          method: post
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"

  getYealyTicketInfo:
    handler: src/tickets.getYealyTicketInfo
    events:
      - http:
          path: getYealyTicketInfo/{year}
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"

resources:
  Resources:
    TicketsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: year
            AttributeType: S
        KeySchema:
          -
            AttributeName: year
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: 'tickets'
